# Generated by Django 3.2.5 on 2021-08-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('description', models.CharField(max_length=500)),
                ('proficiency', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('working_muscles', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('difficulty', models.IntegerField()),
                ('click_count', models.IntegerField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='general.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('workout', models.ManyToManyField(related_name='workout_list', to='general.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('boyun', models.FloatField()),
                ('omuz', models.FloatField()),
                ('sag_kol', models.FloatField()),
                ('sol_kol', models.FloatField()),
                ('bel', models.FloatField()),
                ('alt_karin', models.FloatField()),
                ('sag_bacak', models.FloatField()),
                ('sol_bacak', models.FloatField()),
                ('kalca', models.FloatField()),
                ('sag_on_kol', models.FloatField()),
                ('sol_on_kol', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('omuz_bel_orani', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('target_height', models.FloatField()),
                ('target_boyun', models.FloatField()),
                ('target_sag_kol', models.FloatField()),
                ('target_sol_kol', models.FloatField()),
                ('target_bel', models.FloatField()),
                ('target_alt_karin', models.FloatField()),
                ('target_sag_bacak', models.FloatField()),
                ('target_sol_bacak', models.FloatField()),
                ('target_kalca', models.FloatField()),
                ('target_sag_on_kol', models.FloatField()),
                ('target_sol_on_kol', models.FloatField()),
                ('target_body_fat', models.FloatField()),
                ('target_omuz_bel_orani', models.FloatField()),
                ('followers', models.ManyToManyField(blank=True, related_name='trainee', to='general.Trainer')),
                ('workout_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='general.workoutlist')),
            ],
        ),
    ]
