# Generated by Django 3.2.5 on 2021-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210811_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='alt_karin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='bel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='boyun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='kalca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='omuz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='omuz_bel_orani',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sag_bacak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sag_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sag_on_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sol_bacak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sol_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sol_on_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_alt_karin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_bel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_boyun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_kalca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_omuz_bel_orani',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_sag_bacak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_sag_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_sag_on_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_sol_bacak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_sol_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_sol_on_kol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
