# Generated by Django 3.2.5 on 2021-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210812_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='followers',
            new_name='follows',
        ),
    ]
