# Generated by Django 3.2.5 on 2021-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_trainee_workout_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='target_omuz',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
