# Generated by Django 3.2.5 on 2021-08-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20210820_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='is_admin',
            new_name='is_trainer',
        ),
    ]
