# Generated by Django 3.2.5 on 2021-08-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_trainer_is_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='is_trainer',
        ),
    ]
