# Generated by Django 3.2.5 on 2021-08-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20210824_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.IntegerField(choices=[(0, 'Yoga'), (1, 'Push'), (2, 'Pull'), (3, 'Legs'), (4, 'Upper'), (5, 'Lower'), (6, 'Shoulders'), (7, 'Pectoral'), (8, 'ABS'), (9, 'Arms'), (10, 'Back'), (11, 'Boxing'), (12, 'Swimming'), (13, 'Gym_cardio'), (14, 'Bodyweight_cardio'), (15, 'Calisthenics')], default=0),
        ),
    ]
