# Generated by Django 3.2.5 on 2021-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20210826_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='click_count',
            field=models.IntegerField(null=True),
        ),
    ]
