# Generated by Django 3.2.5 on 2021-08-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_alter_workout_click_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='workout_list',
        ),
        migrations.AddField(
            model_name='trainee',
            name='workout_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainee', to='general.Workout'),
        ),
        migrations.DeleteModel(
            name='WorkoutList',
        ),
        migrations.AddField(
            model_name='status',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='general.trainee'),
        ),
        migrations.AddField(
            model_name='status',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='general.workout'),
        ),
    ]
