# Generated by Django 3.2.5 on 2021-09-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_auto_20210830_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='status',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='follows',
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.IntegerField(choices=[(0, 'todo'), (1, 'done')], default=0),
        ),
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainee', to='general.status'),
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workout', to='general.status'),
        ),
    ]
