# Generated by Django 3.2.5 on 2021-09-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20210902_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='statuses',
        ),
        migrations.AlterField(
            model_name='trainee',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='general.status'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='general.status'),
        ),
    ]
