# Generated by Django 3.2.5 on 2021-09-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_auto_20210903_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='statuses',
            field=models.CharField(choices=[(0, 'To Do'), (1, 'Done')], default='To Do', max_length=30),
        ),
    ]
