# Generated by Django 3.2.5 on 2021-09-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_alter_status_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='general.trainee'),
        ),
        migrations.AddField(
            model_name='status',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='general.workout'),
        ),
    ]
